# ==========================
# Renux OS Cargo Configuration
# ==========================

# Build settings for Renux OS
[build]
# Flags for the Rust compiler
linker = "mold" # Use the mold linker for faster linking
rustflags = [
    "-C", "opt-level=z",   
]
# build-std settings
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

# ===========================
# Rust Configuration targets
# ===========================


# ============================
# Target-specific settings
# ============================


# AMD64
[target.'x86_64-renux']
linker = "mold"
# Set rustflags for the Renux AMD64 target
rustflags = [
    "-Z", "unstable-options",
    "-C", "linker-flavor=gnu",
]

# ARM64 (EXPERIMENTAL)
[target.'aarch64-renux']
linker = "mold"
# Set rustflags for the Renux ARM64 target
rustflags = [
    "-Z", "unstable-options",
    "-C", "linker-flavor=gnu",
]
