name: Build Renux OS (X86_64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rust-src
        profile: minimal

    - name: Install LLVM and clang
      run: sudo apt install llvm llvm-dev clang
    - name: Set nightly as default
      run: rustup default nightly

    - name: Add target
      run: rustup target add x86_64-unknown-none

    - name: Install bootimage in cargo
      run: cargo install bootimage
    - name: Install LLVM Tools preview(cargo)
      run: rustup component add llvm-tools-preview
    - name: Build
      run: cargo bootimage -p main --target=config/arch/x86_64-renux.json -j $(nproc) -vv
